spring:
  application:
    name: omni-health-app
  datasource:
    url: jdbc:mysql://localhost:3306/omni-health
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
  #dev-tool
  devtools:
    livereload:
      enabled: true
#auth
omni:
  auth:
    secret: YSb7nYZBoEOfNvVVhKM2vd2WaO9pEUOwHISWiPt/itkWEB599BrDnCLBWt0C/xPg11y2Spa9T8SgSlSUDHUaSQ== #64 character secret key
    expiration: 43200000 #12 hours in milliseconds