spring:
  application:
    name: omni-health-app
  datasource:
    url: jdbc:mysql://localhost:3306/omni_health
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  # Flyway configuration
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  #dev-tool
  devtools:
    livereload:
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: <<your email>> # your email
    password: <<password>> #your email app passowrd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#auth
omni:
  auth:
    secret: DqY69Wv3kGxI5aM4eXJxW65ZNMnU8rM62d/HZOm6T6tcTTB9ZUE3qvCefrKvzo3fF6DCR1Ip1au1OxB1PkQXJQ== #128 char secret
    expiration: 43200000 #12 hours in milliseconds

aws:
  s3:
    bucket-name: ${S3_BUCKET_NAME:omni-health-bucket}
  region: ${AWS_REGION:us-east-1}
  endpoint: ${AWS_ENDPOINT_URL:http://localhost:4566}
